[package]
name = "rusty_gui"
version = "0.1.1"
edition = "2021"
description = "This is a simple GUI library for Rust."
license = "Apache-2.0"
repository = "https://github.com/Anglebase/Rusty_GUI.git"

[dependencies]
colored = "2.1.0"
chrono = "0.4"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
    "winuser",
    "libloaderapi",
    "wingdi",
    "errhandlingapi",
    "processthreadsapi",
] }

[features]
default = ['log_enabled']
log_enabled = []
log_disabled = []