[package]
name = "rusty_gui"
version = "0.1.1"
edition = "2021"

[dependencies]
colored = "2.1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
    "winuser",
    "libloaderapi",
    "wingdi",
    "errhandlingapi",
    "processthreadsapi",
] }
